### ISSUE TITLE
cyffld2 fails to run on Menpo CI

### ISSUE THREAD

**Issue by jabooth** [menpo/cyffld2#6]
```
dyn1137-72:_t_env jenkins$ ./bin/python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import cyffld2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jenkins/miniconda/1/x64/conda-bld/conda_1484306747272/_t_env/lib/python2.7/site-packages/cyffld2/__init__.py", line 1, in <module>
    from .detection import (detect_objects, detect_frontal_faces,
  File "/Users/jenkins/miniconda/1/x64/conda-bld/conda_1484306747272/_t_env/lib/python2.7/site-packages/cyffld2/detection.py", line 3, in <module>
    from ._ffld2 import FFLDMixture, cy_detect_objects
ImportError: dlopen(/Users/jenkins/miniconda/1/x64/conda-bld/conda_1484306747272/_t_env/lib/python2.7/site-packages/cyffld2/_ffld2.so, 2): Library not loaded: @rpath/libjpeg.8.dylib
  Referenced from: /Users/jenkins/miniconda/1/x64/conda-bld/conda_1484306747272/_t_env/lib/python2.7/site-packages/cyffld2/_ffld2.so
  Reason: image not found
>>>
```

**Comment by patricksnape** [comment]
We need to pin libjpeg
